name: struktr
favicon: null
layout_spectrum: 0.4882102294359356
typography_spectrum: 0.5777996494434774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#000000'
    - '#5f5f5f'
    - '#d3d3d3'
    - '#949494'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
