name: struktr
favicon: null
layout_spectrum: 0.4882102294359356
typography_spectrum: 0.5777996494434774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6755179087631404
  lightness: 0.5428029261529446
  saturation: 0.8861288155894727
  rhythmicContrast: 0.9588738773018122
purpose: []
