name: struktr
favicon: null
layout_spectrum: 0.4882102294359356
typography_spectrum: 0.5777996494434774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f0f3'
    - '#242124'
    - '#787578'
    - '#c0bec1'
    - '#9e9b9e'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
